baseURL = '/'
title = 'KGP'
theme = 'kokoro'

disableKinds = ['taxonomy']

[outputs]
home = ['HTML', 'RSS', 'JSON']

[markup.goldmark.renderer]
  unsafe = true

[languages.en]
  languageName = 'English'
  weight = 1
